### ISSUE TITLE
Deleting range of annotations produces error

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#227]
Tested with: branch master (f40361ef)

Shift-selecting a range of annotations and pressing the Delete Icon produces an error:
* Reset to sample project
* In the timeline, click on the first annotation of the first track ('MGM Title Card')
* Shift-click on the third annotation in the same track ('Credits'). This selects the first four annotations
* Click the delete button in the Toolbar.
* Annotations are not deleted
* Selection is stuck. Cannot deselect annotations or select other annotations.
* Error in console:
```
core.js:6237 ERROR TypeError: Cannot read property 'filter' of undefined
    at embedAnnotations (http://localhost:4200/main.js:5844:35)
    at http://localhost:4200/main.js:7676:114
    at http://localhost:4200/vendor.js:107826:54
    at http://localhost:4200/vendor.js:105880:16
    at ArrayMapNode.push../node_modules/immutable/dist/immutable.es.js.ArrayMapNode.iterate.HashCollisionNode.iterate (http://localhost:4200/vendor.js:106278:9)
    at Map.__iterate (http://localhost:4200/vendor.js:105878:18)
    at Set.__iterate (http://localhost:4200/vendor.js:107826:22)
    at Set.forEach (http://localhost:4200/vendor.js:108212:17)
    at reducer (http://localhost:4200/main.js:7673:21)
    at combination (http://localhost:4200/vendor.js:95994:37)
```

**Comment by martinleopold** [comment]
> From: "adrian.soluch@gmail.com" <adrian.soluch@gmail.com>
> Date: 4. August 2020 at 11:34:25 CEST
> 
> #227
> altes issue, bereits vor meinen ersten änderungen vorhanden gewesen (checkout commit 23925a894ececf6fae6a95e1d25dfe6826a55a77 - letztes vor meinen ersten changes: dinony committed on 26 Feb 2019)
> - dasselbe issue existierte dort schon
> 
> core.js:1673 ERROR TypeError: Cannot read property 'filter' of undefined
>     at embedAnnotations (http://localhost:4200/main.js:3280:33)
>     at http://localhost:4200/main.js:5169:116
>     at http://localhost:4200/vendor.js:71833:54
>     at http://localhost:4200/vendor.js:69887:16
>     at ArrayMapNode.push../node_modules/immutable/dist/immutable.es.js.ArrayMapNode.iterate.HashCollisionNode.iterate (http://localhost:4200/vendor.js:70285:9)
>     at Map.__iterate (http://localhost:4200/vendor.js:69885:18)
>     at Set.__iterate (http://localhost:4200/vendor.js:71833:22)
>     at Set.forEach (http://localhost:4200/vendor.js:72219:17)
>     at reducer (http://localhost:4200/main.js:5166:21)
>     at combination (http://localhost:4200/vendor.js:60158:35)
